#!/bin/sh

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Basic window config
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors (basic for now)
bspc config focused_border_color "#6CA6CD"
bspc config normal_border_color  "#2E5A88"
